### PR TITLE
Successful UI experiments ^^

### PR DESCRIPTION
**Pull request by Mordonus**

### CODE REVIEW

**Comment by Insanitylious** [comment]
After finishing my own app, I'll gladly help with this project  :)

**Comment by Mordonus** [comment]
Do as you wish :) I'm going to experiment with hummingbird now ^^.

**Comment by Insanitylious** [comment]
Powodzenia ^^

**Comment by Mordonus** [comment]
Bry xd

**Comment by Insanitylious** [comment]
Witam witam XD

**Pull request merged**
