### PR TITLE
Performance Improvements (MAJOR)

### PR DESCRIPTION
**Pull request by Mordonus**

### CODE REVIEW

**Comment by Insanitylious** [comment]
To be honest, I've yet to see slow downs, but optimization is always welcome :)

**Comment by Mordonus** [comment]
It may not be an issue for smaller lists or day to day watching increments but I've salvaged about 100MiB worth of memory on ~400 items list + reduced CPU utilisation.It just had to be done.

**Comment by Mordonus** [comment]
Having code copy/pasted to mobile version it *feels* much smoother. ^^

**Comment by Insanitylious** [comment]
Hehe, the magic of UWP

**Comment by Mordonus** [comment]
Magic of not creating bazilions of flyouts...

**Pull request merged**
